### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by jmoseley** [pandoc/actions#3]
It would be useful to have an option to use a cache so we can skip the install process.

**Comment by tarleb** [comment]
Thanks for the suggestion. I don't think I understand what you have in mind, could you give an example of an action that does something similar?

**Comment by jmoseley** [comment]
For sure! The [setup-node](https://github.com/actions/setup-node) action uses caching to save you from needing to fetch and install all your packages for every build.

**Comment by tarleb** [comment]
Thank you, that helps. So the goal would be for the action to cache things like filters and custom templates installed via other means?

**Comment by jmoseley** [comment]
That would probably be very helpful (though I don't use those currently). I was thinking about caching the apt step somehow, so that it does not need to download and unpack if possible. I came across this action, and was considering moving to use it instead (we run on ubuntu, so apt works just fine for us). https://github.com/marketplace/actions/cache-apt-packages

**Comment by tarleb** [comment]
The files that the action downloads come from GitHub, so I don't think we'd save much by caching.

I'll close this for now, simply because I can't think of a good way in which we can use a cache effectively, and without making things overly complicated. But I'd be happy to reopen if there's a clear path forward that I failed to see.

**Comment by jmoseley** [comment]
Thanks for the consideration.
